    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Setup Java JDK
            uses: actions/setup-java@v2
            with:
                distribution: 'adopt'
                java-version: '11'
          - uses: education/autograding@v1
        timeout-minutes: 3
